name: '${name}'
description: 'Demo plugin to show the capabilities of ${name}.'
version: ${version}
authors: [ 'Fulminazzo' ]
main: ${group}.${name_lower}.${name}
api-version: '1.13'
folia-supported: true

commands:
  ${name_lower}reload:
    description: 'Reloads the plugin.'
    usage: '/<command>'
    permission: ${name_lower}.${name_lower}reload
    aliases: ['bsreload']
  hello:
    description: 'Replies with the string "world" translated accordingly to the current configuration.'
    usage: '/<command>'
    permission: ${name_lower}.hello
    aliases: ['hi']
  setlocale:
    description: 'Updates the locale stored for the user'
    usage: '<red>/setlocale <dark_gray><<white>locale<dark_gray>>'
    permission: ${name_lower}.setlocale
  lastdeath:
    description: 'Gets the time since last death of the user'
    usage: '<red>/lastdeath'
    permission: ${name_lower}.lastdeath

permissions:
  ${name_lower}.${name_lower}reload:
    description: 'Permission to execute command /blocksmithreload'
    default: op
  ${name_lower}.hello:
    description: 'Permission to execute command /hello'
    default: true
  ${name_lower}.setlocale:
    description: 'Permission to execute command /setlocale'
    default: true
